#pragma once
#define 如果介个 if 
#define 整个整数 int
#define 整个字符  char
#define 整个小数 float
#define 整个长整数 long 
#define 整个长小数 double
#define 整个短整数 short
#define 啥都没有 void 
#define 使劲整 do  
#define 新整一个 new 
#define 老铁比划一下 try 
#define 其他嘞情况 else 
#define 搁这情况的时候 while 
#define 有符号嘞 signed 
#define	没符号嘞 unsigned 
#define	自动嘞baby auto 
#define	杵着不动 static 
#define	搁外边整嘞 extern 
#define	比划一下多大 sizeof 
#define 滚犊子 delete 
#define	扔一边去 throw 
#define	非常坚定嘞 const 
#define	整个类 class 
#define	老铁 friend 
#define	回家嘞 return 
#define	老铁挑一挑 switch 
#define	大家伙嘞 public 
#define	铁子伙条裤子穿 union 
#define	铁子传送 goto 
#define	整个运算符 operator 
#define	整个榜样 template
#define	枚举一下 enum 
#define	自己私人嘞 private 
#define 就介个 this 
#define 虚拟嘞 vitrual 
#define 搁这个情况 case 
#define 一般嘞情况 default 
#define 行内展开伙计 inline 
#define 保护嘞 protected 
#define	整个结构体 struct 
#define 搁这函数开整 main 
#define	括一下 (
#define 再括一下 )
#define 开整 {
#define 整完了事 }
#define 伙计来个循环 for 
#define 整个字符串 string
#define 老弟你跟我听好了 cout<<
#define 你给我记住喽 << endl